apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  annotations:
    storageclass.kubernetes.io/is-default-class: "false"
  labels:
    local.storage.openshift.io/owner-name: local-block
    local.storage.openshift.io/owner-namespace: openshift-local-storage
  name: localblock

